baseURL = "https://RyanStokes.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Ryan Stokes"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Ryan Stokes"
author = "Ryan Stokes"
description = "Data Scientist | Statistician | Cognitive Scientist"
profilePicture = "images/profile.jpg"
resumeDocument = "images/Ryan Stokes Resume.pdf"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

[markup]
  defaultMarkdownHandler = "blackfriday"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ryan-stokes-37a20a157/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/RyanStokes"

#[[params.socialIcons]]
#icon = "fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:RyanStokes@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "post"
  url = "/projects/"

  [[menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/cv/"